version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: local_mongo
    ports:
      - "27018:27017" # Mapeia a porta 27017 do contêiner para a porta 27018 do host
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  mongo_data: